services:
  - type: web
    name: massimo-furness-portfolio
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 22
    autoDeploy: true
    healthCheckPath: /
